let DB={};
const $=id=>document.getElementById(id);
function sma(a,n){return a.length<n?null:a.slice(-n).reduce((x,y)=>x+y,0)/n}
function ema(a,n){if(a.length<n)return[];let e=a.slice(0,n).reduce((x,y)=>x+y,0)/n,k=2/(n+1),o=[e];for(let i=n;i<a.length;i++){e=a[i]*k+e*(1-k);o.push(e)}return o}
function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];if(d>=0)g+=d;else l-=d}if(l===0)return 100;let rs=(g/n)/(l/n);return 100-100/(1+rs)}
function macd(a){if(a.length<35)return null;let e12=ema(a,12),e26=ema(a,26),m=[];for(let i=0;i<e26.length;i++){let j=i+14;if(e12[j]!==undefined)m.push(e12[j]-e26[i])}if(m.length<9)return null;let line=m.at(-1),sig=ema(m,9).at(-1);return{line,signal:sig,hist:line-sig}}
function score(c){let a=c.closes,price=c.price??a.at(-1),ma20=sma(a,20),ma50=sma(a,50),R=rsi(a),M=macd(a),s=50,rs=[];if(R!==null){if(R>=55&&R<70){s+=12;rs.push("RSI momentumu olumlu")}else if(R>=70){s-=8;rs.push("RSI aşırı alım bölgesinde")}else if(R<35){s+=8;rs.push("RSI düşük")}else rs.push("RSI nötr")}if(price&&ma20){if(price>ma20){s+=8;rs.push("fiyat MA20 üzerinde")}else{s-=6;rs.push("fiyat MA20 altında")}}if(price&&ma50){if(price>ma50){s+=10;rs.push("fiyat MA50 üzerinde")}else{s-=8;rs.push("fiyat MA50 altında")}}if(M){if(M.hist>0){s+=10;rs.push("MACD pozitif")}else{s-=8;rs.push("MACD negatif")}}s=Math.max(0,Math.min(100,Math.round(s)));let trend=price&&ma20&&ma50?(price>ma20&&ma20>ma50?"📈 Güçlü Pozitif":price>ma20?"📈 Pozitif":price<ma20&&price<ma50?"📉 Negatif":"➡️ Nötr"):"➡️ Nötr";let risk=R!==null&&(R>72||R<28)?"Yüksek":s>=70?"Orta":"Yüksek";let signal=s>=75?"OLUMLU":s>=55?"NÖTR-POSİTİF":s>=40?"NÖTR":"RİSKLİ";return{s,ma20,ma50,R,M,trend,risk,signal,rs}}
function render(sym){let c=DB[sym];if(!c){$("comment").textContent=`${sym} için güncel veri dosyasında kayıt yok. Bir sonraki veri güncellemesinde listeye eklenebilir.`;return}let a=score(c),p=c.price??c.closes.at(-1);$("company").textContent=sym;$("price").textContent=p.toLocaleString("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:2});$("change").textContent=c.changePercent==null?"—":`${c.changePercent.toFixed(2)}%`;$("updated").textContent=c.date||"—";$("score").textContent=a.s;$("meter").style.width=a.s+"%";$("signal").textContent=a.signal;$("trend").textContent=a.trend;$("trendText").textContent=a.rs.slice(0,2).join(" • ");$("risk").textContent=a.risk;$("riskText").textContent=`RSI ${a.R?.toFixed(1)??"—"} • ${c.closes.length} günlük kapanış`;$("rsi").textContent=a.R?.toFixed(1)??"—";$("macd").textContent=a.M?(a.M.hist>=0?"Pozitif":"Negatif"):"—";$("ma20").textContent=a.ma20?(p>=a.ma20?"Üzerinde":"Altında"):"—";$("ma50").textContent=a.ma50?(p>=a.ma50?"Üzerinde":"Altında"):"—";$("comment").textContent=`${sym} teknik AI skoru ${a.s}/100. ${a.rs.join(". ")}. Haber, bilanço ve KAP verileri bu sürümün skoruna dahil değildir.`}
async function init(){try{let r=await fetch("data.json?"+Date.now());if(!r.ok)throw Error();DB=await r.json();let syms=Object.keys(DB);$("status").textContent=`● Veri hazır • ${syms.length} hisse • son güncelleme ${DB._meta?.updatedAt||"—"}`;let list=$("stockList");list.innerHTML="";syms.filter(x=>x!=="_meta").forEach(s=>{let b=document.createElement("button");b.className="stock";b.textContent=s;b.onclick=()=>{$("symbol").value=s;render(s)};list.appendChild(b)});render($("symbol").value.toUpperCase())}catch(e){$("status").textContent="● Veri dosyası henüz oluşmadı";$("comment").textContent="GitHub Actions veri güncellemesi tamamlandığında burada fiyat ve teknik analiz görünecek."}}
$("analyzeBtn").onclick=()=>render($("symbol").value.trim().toUpperCase());$("symbol").onkeydown=e=>{if(e.key==="Enter")render($("symbol").value.trim().toUpperCase())};init();